name: GitHub Actions Demo
run-name: blah blah ${{ github.actor }} are they the same or different vms god
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-2025
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: hostname
      - run: Get-NetIPAddress
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  sadness_1:
    runs-on: windows-2025
    steps:
      - run: echo SAD1b
      - run: hostname
      - run: Get-NetIPAddress
  sadness_2:
    runs-on: windows-2025
    steps:
      - shell: cmd
        env:
          KORI: ${{ secrets.KOSAK_ORIENTATION }}
        run: |
          echo "%HOSTNAME%"
          echo "%KORI%"
